config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :spots

end

app/models/spot.rb
class Spot < ActiveRecord::Base

	validates :position_x, :position_y,presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 100,less_than_or_equal_to: 900  }
	validate  :collision_check #validates if there is a collision between new/updated and already stored spot


	def collision_check
		
		#second validation required due to lack of possibility to change validations order 
		#(when one of position is empty it is not possible to check collisions)				
		if (!self.position_x.nil? && (self.position_x.is_a? Integer) && !self.position_y.nil? && (self.position_y.is_a? Integer))
			Spot.all.each do |spot|
				# self excluded from collision check to be able to update position by very small (less than 24) value
				if (spot.id != self.id && !(spot.position_x > self.position_x+24 || spot.position_x+24 < self.position_x || spot.position_y > self.position_y+24 || spot.position_y+24 < self.position_y))
					errors.add(:base, "Coordinates error: collision with existing spot: #{spot.name} ")
				end

			end
		end	
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@spots = Spot.all
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    # automatically adding standard spot name - "Spot spot.id"
    @spot.name = "Spot "+(Spot.maximum(:id).to_i + 1).to_s if @spot.name.empty?
    respond_to do |format|
      if @spot.save
        format.js
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.js
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    @origSpot = Spot.find(@spot.id)
    respond_to do |format|
      if @spot.update(spot_params)
        format.js
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.js
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:position_x, :position_y, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/home/index.html.erb
<%= image_tag "s_grid.png", id: "grid", title: "Click to add a new spot"%>
<div id="spots">
	<%= render @spots %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragDrop - Piotr Pszczoła</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>

</html>

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br>
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.number_field :y %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/_spot.html.erb
<p id="spot<%= spot.id %>" class="spot ui-widget-content" style="position: absolute; left: <%= spot.position_x %>px; top: <%= spot.position_y %>px;" title="<%= spot.name %>"></p> <%= p "\n" %>

app/views/spots/create.js.erb
//if any error encountered - print them all, if not - show newly added point and message with new point info
<% if @spot.errors.any? %>
   
    <% @spot.errors.full_messages.each do |message| %>
        alert("\n<%= message %>\n");
    <% end %>
<% else %>
	// when no errors render new point with possibility to change position by drag-drop feature
    $("<%= j (render @spot) %>").appendTo("#spots").draggable({
    	stop: function( event, ui ) {
    		var spotId = event.target.id.match(/\d+/)
    		$.ajax({
	  			method: "PATCH",
	  			url: "<%= spot_path(@spot) %>",
	  			data: { spot: {position_x: $(this).position().left, position_y: $(this).position().top} }
			})
    	}
    });

    alert("Spot with position x: <%= @spot.position_x %> y: <%= @spot.position_y %> and name: <%= @spot.name%> successfully created!\n");
    
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Spots</h1>

<table>
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= spot.position_x %></td>
        <td><%= spot.position_y %></td>
        <td><%= spot.name %></td>
        <td><%= link_to 'Show', spot %></td>
        <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
        <td><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @spot.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @spot.y %>
</p>

<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>

app/views/spots/update.js.erb
<% if @spot.errors.any? %>
	var errors = '';
    <% @spot.errors.full_messages.each do |message| %>
        errors += '<%= message %>\n';
    <% end %>
    alert(errors);
    
    // in case of errors render original spot with possibility to change position by drag-drop feature
    $("#spot<%=@spot.id%>").remove();
    $("<%= j (render @origSpot) %>").appendTo("#spots").draggable({
    	stop: function( event, ui ) {
    		var SpotId = event.target.id.match(/\d+/)
    		$.ajax({
	  			method: "PATCH",
	  			url: "/spots/"+SpotId,
	  			data: { spot: {position_x: $(this).position().left, position_y: $(this).position().top} }
			})
    	}
    });
<% else %>
    alert("Update succeeded");
<% end %>